-- ============================================================
-- SingleCart - Virtual Mall Platform Database Initialization
-- Execute this script in your Supabase SQL Editor
-- Completely idempotent: safe to run multiple times
-- ============================================================

-- 1. Create custom Role Type for dashboard security
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('retailer', 'admin');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Profiles Table to store Retailers and Admins
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  shop_name TEXT, -- NULL for global admin
  role user_role NOT NULL DEFAULT 'retailer'::user_role,
  category TEXT DEFAULT 'General',
  banner_url TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Products Table (Each product belongs to a specific retailer)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retailer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g., 'Fashion', 'Cafes', 'Electronics', 'Beauty', 'Home'
  price NUMERIC NOT NULL,
  image_url TEXT,
  badge TEXT,
  description TEXT,
  in_stock BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Customer Orders Table (Does NOT require a customer user_id)
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retailer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  delivery_notes TEXT, -- e.g., 'Table No. 5', 'Curbside Bay A', 'Pickup counter'
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending' NOT NULL, -- 'Pending', 'Preparing', 'Ready', 'Completed', 'Cancelled'
  delivery_otp TEXT, -- 4-digit security PIN for doorstep Cash-on-Delivery verification
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ensure delivery_otp column exists if upgrading existing tables
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_otp TEXT;

-- 5. Store Registration Applications Table (Retailer Self-Registration)
CREATE TABLE IF NOT EXISTS public.store_applications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  applicant_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  store_name TEXT NOT NULL,
  department TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'Pending' NOT NULL, -- 'Pending', 'Approved', 'Rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES (IDEMPOTENT)
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_applications ENABLE ROW LEVEL SECURITY;

-- PROFILES POLICIES
DROP POLICY IF EXISTS "Anyone can view retailer profiles" ON public.profiles;
CREATE POLICY "Anyone can view retailer profiles" 
ON public.profiles FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Users can insert profiles" ON public.profiles;
CREATE POLICY "Users can insert profiles" 
ON public.profiles FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Users can edit their own profile" ON public.profiles;
CREATE POLICY "Users can edit their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- PRODUCTS POLICIES
DROP POLICY IF EXISTS "Anyone can browse products" ON public.products;
CREATE POLICY "Anyone can browse products" 
ON public.products FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Retailers can modify their own products" ON public.products;
CREATE POLICY "Retailers can modify their own products" 
ON public.products FOR ALL 
USING (auth.uid() = retailer_id);

-- ORDERS POLICIES
DROP POLICY IF EXISTS "Anonymous customers can place orders" ON public.orders;
CREATE POLICY "Anonymous customers can place orders" 
ON public.orders FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Retailers can only view their own store orders" ON public.orders;
CREATE POLICY "Retailers can only view their own store orders" 
ON public.orders FOR SELECT 
USING (
  auth.uid() = retailer_id 
  OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

DROP POLICY IF EXISTS "Retailers can update their order statuses" ON public.orders;
CREATE POLICY "Retailers can update their order statuses" 
ON public.orders FOR UPDATE 
USING (
  auth.uid() = retailer_id
  OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

DROP POLICY IF EXISTS "Retailers or Admins can delete orders" ON public.orders;
CREATE POLICY "Retailers or Admins can delete orders" 
ON public.orders FOR DELETE 
USING (
  auth.uid() = retailer_id
  OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

-- STORE APPLICATIONS POLICIES
DROP POLICY IF EXISTS "Anyone can submit store application" ON public.store_applications;
CREATE POLICY "Anyone can submit store application" 
ON public.store_applications FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view and manage store applications" ON public.store_applications;
CREATE POLICY "Admins can view and manage store applications" 
ON public.store_applications FOR ALL 
USING (true);

-- ============================================================
-- REALTIME SUBSCRIPTIONS (IDEMPOTENT)
-- ============================================================

DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'orders'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'store_applications'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.store_applications;
    END IF;
  END IF;
END $$;
